### PR TITLE
Assistant/easy comment

### PR DESCRIPTION
**Pull request by Monsterdied**
Changed the port from 3000 to 8080, and added some features, parsing for c++ c# and more, changed the name of the dockerfile, from dockerfile to Dockerfile

### CODE REVIEW

**Review by just4THEsmile — COMMENTED** [review]
looks good, did not found anything wrong with it

**Review by just4THEsmile — APPROVED** [review]

**Comment by koaLaMoucho** [comment]
looks like everything is working

**Review by koaLaMoucho — APPROVED** [review]
looks good, everything works fine

**Comment by Monsterdied** [comment]
ok thank you for your time

**Pull request merged**
