### PR TITLE
Sprint 1 frontend for FeatureCraft

### PR DESCRIPTION
**Pull request by ricardo-peralta-0000**
This pull request includes several changes to the `avengers/frontend/webapp` project done to integrate the Featurecraft assistant. The changes include updates to the `package.json` file.

### Dependency Updates:

* **Package Updates:**
  - Added `axios` and `react-markdown` dependencies to `package.json` to support Gemini response rendering with markdown styling and easier requests.

### Featurecraft Assistant Implementation:

1. Assistant Structure:
The assistant frontend code is placed on `avengers/frontend/webapp/src/app/assistants/featurecraft`.

avengers/frontend/webapp/src/app/assistants/featurecraft/
├── [id]/
│   └── page.js
├── hooks/
│   └── useFeaturecraftAssistant.js
├── components/
│   └── ui/
│               └── conversationNotFound.jsx
│   └── assistant.js
│   └── messageBlock.js
│   └── newMessageBlock.js
├── page.js

2. Assistant usage:
The assistant can be accessed in the url path `/assistants/featurecraft` where it integrates into the existing UI. The existing history side bar now uses the backend endpoint to obtain the chat's history. On the side is the component from `assistant.js` where a user can start a new conversation.
Default Assistant URL
By clicking on a history  item the user can then move to an existing conversation in order to see its history or continue it where it was left off. The user is routed dynamically to  `/assistants/featurecraft/[conversationId]`.
Example of an existing conversation

* `avengers/frontend/webapp/src/app/assistants/featurecraft/[id]/page.js`: Implemented the `FeaturecraftConversationPage` component, which manages the conversation state and fetches conversation history. 
* `avengers/frontend/webapp/src/app/assistants/featurecraft/components/assistant.js`: Added the `FeaturecraftAssistant` component to handle message interactions and display the conversation. It interact with the hook and is meant to have different behaviours for new conversations and existing ones.
* `avengers/frontend/webapp/src/app/assistants/featurecraft/hooks/useFeaturecraftAssistant.js`: Created a custom hook `useFeaturecraftAssistant` to manage the assistant's state and handle message sending and receiving.

### CODE REVIEW

**Review by wallX — DISMISSED** [review]
Parece estar tudo bem, corri do meu lado e não pareceu haver problemas

**Review by martimUp — APPROVED** [review]

**Comment by ricardo-peralta-0000** [comment]
Did rebase to the main in order to be able to close the pull request. Everything seems to be working

**Review by martimUp — APPROVED** [review]

**Review by df624 — APPROVED** [review]
Seems fine

**Review by martimUp — APPROVED** [review]
Everything looks alright

**Review by danrpinho — DISMISSED** [review]

**Review by martimUp — APPROVED** [review]
Looks fine

**Review by danrpinho — DISMISSED** [review]

**Review by martimUp — APPROVED** [review]

**Comment by aaguiar** [comment]
I only read the code and it seems good. I trust that it runs.

**Review by aaguiar — APPROVED** [review]

**Comment by aaguiar** [comment]
@cosmicblackcat and @lessthelonely will review and check all details.

**Review by lessthelonely — CHANGES_REQUESTED** [review]
While the code reads OK, there are build issues.

image

If this is over a .gitignore configuration, it should be pretty easy to fix. Either way, make sure that _**even people who haven't been involved in developing this**_ can run it. Try a computer where nothing from the project is present and see if you can run it, if needed.

**Comment by ricardo-peralta-0000** [comment]
@lessthelonely Can you perhaps give indication of where that error occurs. I tried installing the repository clean, changed to the branch and did `npm install` and `npm run dev` and it ran without any issues.

**Comment by lessthelonely** [comment]
> @lessthelonely Can you perhaps give indication of where that error occurs. I tried installing the repository clean, changed to the branch and did `npm install` and `npm run dev` and it ran without any issues.

Just when trying to open your assistant page through the routing ('/assistants/featurecraft/'). The location of the line causing the error in the in the screenshot.

**Comment by ricardo-peralta-0000** [comment]
The error is not appearing to me. When I do that I get 
imagem.
I am using a fresh clone of the repo for that.
I am trying to do what @cosmicblackcat suggested anyway. When I do rebase again it asks for more changes which might be causing the issue. I will try to find out if that is it.

**Comment by ricardo-peralta-0000** [comment]
Okay. I have finished performing the rebase again and used the 

> --force-with-lease

to try and see if it works properly. I cloned the repository again and ran `npm install` and `npm run dev` in the frontend to check if it runs without issue and I could run the code with no build problems. I am leaving a screenshot of what I obtained anyway.
imagem
imagem
imagem
@lessthelonely @cosmicblackcat @danrpinho I am going to request review again and let me know if there is any issue

**Comment by ricardo-peralta-0000** [comment]
> > Okay. I have finished performing the rebase again and used the
> > 
> > > --force-with-lease
> > 
> > to try and see if it works properly. I cloned the repository again and ran `npm install` and `npm run dev` in the frontend to check if it runs without issue and I could run the code with no build problems. I am leaving a screenshot of what I obtained anyway. imagem imagem imagem @lessthelonely @cosmicblackcat @danrpinho I am going to request review again and let me know if there is any issue
> 
> I managed to run it again. Just a quick question (I'll edit this afterwards according to the reply): am I supposed to be able to run the backend? Without it, I can't really see history, but the changes are titles "Sprint 1 frontend", so I am assuming everything is fine. If I am supposed to run the backend, however, do tell! 
> 
> image
> 
> Hope you don't mind me trying to give the assistant an existential crisis ;)

No. That is how it's supposed to be like. This is supposed to be a frontend for sprint 1. So the code won't be testable. However my group tested it ourselves. We simply did not approve the PR for too long which caused all these issues.  The backend will only be added on the current sprint so, for now, it can only be run by us since the code is still in the group repo.

**Review by lessthelonely — APPROVED** [review]

**Comment by lessthelonely** [comment]
> > > Okay. I have finished performing the rebase again and used the
> > > > --force-with-lease
> > > 
> > > 
> > > to try and see if it works properly. I cloned the repository again and ran `npm install` and `npm run dev` in the frontend to check if it runs without issue and I could run the code with no build problems. I am leaving a screenshot of what I obtained anyway. imagem imagem imagem @lessthelonely @cosmicblackcat @danrpinho I am going to request review again and let me know if there is any issue
> > 
> > 
> > I managed to run it again. Just a quick question (I'll edit this afterwards according to the reply): am I supposed to be able to run the backend? Without it, I can't really see history, but the changes are titles "Sprint 1 frontend", so I am assuming everything is fine. If I am supposed to run the backend, however, do tell!
> > image
> > Hope you don't mind me trying to give the assistant an existential crisis ;)
> 
> No. That is how it's supposed to be like. This is supposed to be a frontend for sprint 1. So the code won't be testable. However my group tested it ourselves. We simply did not approve the PR for too long which caused all these issues. The backend will only be added on the current sprint so, for now, it can only be run by us since the code is still in the group repo.

Carry on! I approved the changes :)

**Comment by ricardo-peralta-0000** [comment]
> @ricardo-peralta-0000 we, teachers, will only review PRs that relate to the infrastructure folder. For PRs such as these you can tag your colleagues and ask for reviews :)

Yes but the problem occurs because the PR had several days and our teacher recommended us to do rebase to the main to be able to close it. That forced us for some reason to automatically ask for review from the teachers since you have added code to the main in the meanwhile, which influenced the rebase and @danrpinho also couldn't merge. But I can try to remove you now since it seems it already started to be possible.

**Pull request merged**
