### PR TITLE
Integrated EasyComment into AI4SDHELPER

### PR DESCRIPTION
**Pull request by Dragon29R**
Known bugs: 
Fix the local server to the cloud server

Changes:
Modified the shared extension.ts

There were no conflicts

### CODE REVIEW

**Comment by Monsterdied** [comment]
seems good, good job, just try to make the code cleaner

**Review by Monsterdied — COMMENTED** [review]
seems good continue the good work

**Review by just4THEsmile — APPROVED** [review]
looks good

**Review by Monsterdied — APPROVED** [review]
seems good

**Pull request merged**
