### PR TITLE
Assistants/featurecraft/import requirements

### PR DESCRIPTION
**Pull request by wallX**
this PR merges changes made to FeatureCraft that allows users to upload requirements using txt file

### CODE REVIEW

**Review by martimUp — DISMISSED** [review]
looks good

**Comment by ricardo-peralta-0000** [comment]
Hey. You missed that for the local docker you also need to change the secret name.

**Comment by wallX** [comment]
Pronto ja dei update do compose

**Review by ricardo-peralta-0000 — APPROVED** [review]
I found no errors in running and the functionality works.
However, @df624 if you can add a bug item to the board. When uploading the requirements file before typing any message it does not remember the requirements after sending a message. This is unexpected behaviour.

**Review by martimUp — APPROVED** [review]

**Pull request merged**
