### PR TITLE
x-men structure change and readme update

### PR DESCRIPTION
**Pull request by IgorAndrade10**
This pull request changes the position of some assistants frontend and is to only be accepted if at least a member of each of the assistants that where relocated (SARA, WhatTheDuck, ArchiDetect and WardenAI) aproves this pull request.
Old frontend is now called ai4sd and still contains the same code as before and is being reworked by another team.
Each team please check if the behaviour of the assistant stays the same in the new extensions and if the assistant is correctly characterised. If not request changes and i will change it as soon as possible.

### CODE REVIEW

**Review by pedroojanuu — APPROVED** [review]
After understanding the purpose of the structure change and testing, I believe this works as expected.

**Review by Tomas-Gaspar — APPROVED** [review]
Everything concerning WhatTheDuck is working as it should

**Review by tomasvicente3 — APPROVED** [review]
Regarding ArchiDetect, it all seems functional

**Review by MRita443 — APPROVED** [review]
Looks good from SARA! You say no setup is needed in the README, which is not quite true as SARA needs a `.env` but it'll be removed in a PR this sprint so that's ok

**Pull request merged**
