### PR TITLE
Assistants' Integration Proposal and Guide (v2)

### PR DESCRIPTION
**Pull request by jmisidro**
## Created a Guide for the Assistants' Integration into AI4SD. 
This proposal consists of creating a folder for each assistant inside `/avengers/frontend/webapp/src/app/assistants/`. This approach has 2 main benefits:
- Automatically creates a route for the assistant at`/avengers/frontend/webapp/src/app/assistants/ASSISTANT_NAME`, thanks to Next.js folder router - read more about it [here](https://nextjs.org/docs/app/building-your-application/routing).
- Each assistant gets a unique folder to better organize their code and custom components.

I've created a complete guide for each team to get started, located at `/avengers/frontend/webapp/src/app/assistants/README.md`.

image

### CODE REVIEW

**Comment by franciscoribeiro2003** [comment]
Seems nice, I do believe using the advantages of `Next.js` folder router is the best way to integrate all the superhero's frontends together without many conflicts.

**Comment by ricardo-peralta-0000** [comment]
Seems okay and a good way to integrate all the different frontends.

**Review by filipecardoso0 — COMMENTED** [review]
Everything seems fine to me. 
Nice and elegant way to put things

**Review by LuisRelvas — APPROVED** [review]
Everything that was implemented, adds value to the final product.

**Comment by RodrigoCamposRodrigues** [comment]
It seems to me that it is an efficient way of integrating the different assistants. These changes will benefit all the teams.

**Review by RodrigoCamposRodrigues — APPROVED** [review]

**Pull request merged**
