### PR TITLE
Superheroes secrets setup

### PR DESCRIPTION
**Pull request by Vidal322**
Continuation of Pull Request #95 

Since with the last Pull Request the secrets for each super hero and jarvis were not created, I'm attempting to fix this by creating an initial version for each  of them, since that worked with the the cloudbuild-sa-key

### CODE REVIEW

**Review by kikoveiga — APPROVED** [review]

**Comment by kikoveiga** [comment]
From what was mentioned above, I think everything is good about permissions. For now, only 1 secret is created per superhero, can we merge to test if it is working correctly?

**Comment by Vidal322** [comment]
Yes exactly I think with an extra for loop in the superhero secrets you should be good.
About the permissions I think they re all set except for the cloudbuild service account, which I dont remember giving permissions to acess the secrets.

**Comment by kikoveiga** [comment]
I added admin permissions to cloudbuild in my commit, so I think it should be ready for merge!

**Review by kikoveiga — APPROVED** [review]

**Comment by kikoveiga** [comment]
Yes, let's hope it works😅

**Pull request merged**
